
CREATE PROCEDURE [dbo].[sp_InsertOrderHeaderScrub]
(
	@OrderNo varchar(10),
	@Generation varchar(4),
	@PriceBranch varchar(10),
	@ShipBranch varchar(10),
	@OrderDate datetime,
	@RequireDate datetime,
	@ShipDate datetime,
	@InvoiceNo varchar(12),
	@InvoiceDate datetime,
	@OrderStatus varchar(1),
	@BillToID varchar(10),
	@BillTo varchar(50),
	@ShipToID varchar(10),
	@ShipTo varchar(50),
	@ShippingAddressName varchar(75),
	@ShippingAddressAddress varchar(300),
	@ShippingAddressCity varchar(150),
	@ShippingAddressState varchar(10),
	@ShippingAddressZip varchar(15),
	@ShippingAddressPhone varchar(20),
	@CustomerPO varchar(15),
	@OrderBy varchar(35),
	@ReleaseNo varchar(25),
	@Salesperson varchar(30),
	@Writer varchar(30),
	@ShipVia varchar(30),
	@TaxJurisdiction varchar(10),
	@QuoteID varchar(15),
	@Terms varchar(30),
	@Freight numeric(18, 2),
	@Handling numeric(18, 2),
	@Tax numeric(18, 2),
	@FET numeric(18, 2),
	@ServiceChrg numeric(18, 2),
	@Total numeric(18, 2),
	@DueDate datetime,
	@CashDisc numeric(18, 2),
	@WebDisc numeric(18, 2),
	@DiscAmt numeric(18, 2),
	@DiscDate datetime,
	@DiscTaken numeric(18, 2),
	@Deposit numeric(18, 2),
	@AmtPaid numeric(18, 2),
	@ShippingInstr varchar(1000),
	@InternalNotes varchar(1000),
	@ShippingInstrLines varchar(1000),
	@InternalNotesLines varchar(1000),
	@LastUpdateDate datetime,
	@LastUpdateTime datetime,
	@LastUpdateUser varchar(20),
	@LastUpdateComment varchar(500),
	@CreditCard varchar(30),
	@BidExpireDate datetime,
	@CreditCardCardType varchar(10),
	@CreditCardCardNumber varchar(10),
	@CreditCardExpireDate varchar(6),
	@CreditCardCardHolder varchar(30),
	@CreditCardStreetAddress varchar(150),
	@CreditCardPostalCode varchar(15),
	@CreditCardCCVCode varchar(30),
	@CreditCardAuthType varchar(1),
	@CreditCardElementAcctID varchar(50),
	@ShippingAddress varchar(350),
	@ActivityInstanceId uniqueidentifier,
	@id uniqueidentifier output
)
AS
BEGIN
	SET NOCOUNT ON
	SET XACT_ABORT ON

	DECLARE @result TABLE (id uniqueidentifier)

	INSERT OrderHeader_Scrub
	(
		OrderNo,
		Generation,
		PriceBranch,
		ShipBranch,
		OrderDate,
		RequireDate,
		ShipDate,
		InvoiceNo,
		InvoiceDate,
		OrderStatus,
		BillToID ,
		BillTo,
		ShipToID,
		ShipTo,
		ShippingAddressName,
		ShippingAddressAddress,
		ShippingAddressCity,
		ShippingAddressState,
		ShippingAddressZip,
		ShippingAddressPhone,
		CustomerPO,
		OrderBy,
		ReleaseNo,
		Salesperson,
		Writer,
		ShipVia,
		TaxJurisdiction,
		QuoteID,
		Terms,
		Freight,
		Handling,
		Tax,
		FET,
		ServiceChrg,
		Total,
		DueDate,
		CashDisc,
		WebDisc,
		DiscAmt,
		DiscDate,
		DiscTaken,
		Deposit,
		AmtPaid,
		ShippingInstr,
		InternalNotes,
		ShippingInstrLines,
		InternalNotesLines,
		LastUpdateDate,
		LastUpdateTime,
		LastUpdateUser,
		LastUpdateComment,
		CreditCard,
		BidExpireDate,
		CreditCardCardType,
		CreditCardCardNumber,
		CreditCardExpireDate,
		CreditCardCardHolder,
		CreditCardStreetAddress,
		CreditCardPostalCode,
		CreditCardCCVCode,
		CreditCardAuthType,
		CreditCardElementAcctID,
		ShippingAddress,
		ActivityInstanceId
	)
	output inserted.id into @result
	VALUES
	(
		@OrderNo,
		@Generation,
		@PriceBranch,
		@ShipBranch,
		@OrderDate,
		@RequireDate,
		@ShipDate,
		@InvoiceNo,
		@InvoiceDate,
		@OrderStatus,
		@BillToID ,
		@BillTo,
		@ShipToID,
		@ShipTo,
		@ShippingAddressName,
		@ShippingAddressAddress,
		@ShippingAddressCity,
		@ShippingAddressState,
		@ShippingAddressZip,
		@ShippingAddressPhone,
		@CustomerPO,
		@OrderBy,
		@ReleaseNo,
		@Salesperson,
		@Writer,
		@ShipVia,
		@TaxJurisdiction,
		@QuoteID,
		@Terms,
		@Freight,
		@Handling,
		@Tax,
		@FET,
		@ServiceChrg,
		@Total,
		@DueDate,
		@CashDisc,
		@WebDisc,
		@DiscAmt,
		@DiscDate,
		@DiscTaken,
		@Deposit,
		@AmtPaid,
		@ShippingInstr,
		@InternalNotes,
		@ShippingInstrLines,
		@InternalNotesLines,
		@LastUpdateDate,
		@LastUpdateTime,
		@LastUpdateUser,
		@LastUpdateComment,
		@CreditCard,
		@BidExpireDate,
		@CreditCardCardType,
		@CreditCardCardNumber,
		@CreditCardExpireDate,
		@CreditCardCardHolder,
		@CreditCardStreetAddress,
		@CreditCardPostalCode,
		@CreditCardCCVCode,
		@CreditCardAuthType,
		@CreditCardElementAcctID,
		@ShippingAddress,
		@ActivityInstanceId
	)

	SELECT @id = id FROM @result;
END