//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morsco.Customizations.Lib.EmailService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MorscoEmailServiceDatabase : DbContext
    {
        public MorscoEmailServiceDatabase()
            : base("name=MorscoEmailServiceDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProcessedASPNetUsersLog> ProcessedASPNetUsersLogs { get; set; }
        public virtual DbSet<TriggeredSendKeyMap> TriggeredSendKeyMaps { get; set; }
        public virtual DbSet<TriggeredSend> TriggeredSends { get; set; }
    }
}
