//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morsco.Customizations.Lib.EmailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TriggeredSendKeyMap
    {
        public System.Guid SendId { get; set; }
        public string EmailType { get; set; }
        public string CustomerKey { get; set; }
    }
}
