




CREATE VIEW [dbo].[vw_ProductAttributeValues]
AS
		      SELECT [CustomerItemID] ProductName, AttributeName1   [AttributeName], [AttributeValue1] [AttributeValue],1 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName1 <> '' AND AttributeValue1 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName2] [AttributeName], [AttributeValue2] [AttributeValue],2 SortOrder  FROM dbo.TradeServicesProduct s WHERE AttributeName2 <> '' AND AttributeValue2 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName3] [AttributeName], [AttributeValue3] [AttributeValue],3 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName3 <> '' AND AttributeValue3 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName4] [AttributeName], [AttributeValue4] [AttributeValue],4 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName4 <> '' AND AttributeValue4 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName5] [AttributeName], [AttributeValue5] [AttributeValue],5 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName5 <> '' AND AttributeValue5 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName6] [AttributeName], [AttributeValue6] [AttributeValue],6 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName6 <> '' AND AttributeValue6 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName7] [AttributeName], [AttributeValue7] [AttributeValue],7 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName7 <> '' AND AttributeValue7 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName8] [AttributeName], [AttributeValue8] [AttributeValue],8 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName8 <> '' AND AttributeValue8 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName9] [AttributeName], [AttributeValue9] [AttributeValue],9 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName9 <> '' AND AttributeValue9 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName10] [AttributeName], [AttributeValue10] [AttributeValue],10 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName10 <> '' AND AttributeValue10 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName11] [AttributeName], [AttributeValue11] [AttributeValue],11 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName11 <> '' AND AttributeValue11 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName12] [AttributeName], [AttributeValue12] [AttributeValue],12 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName12 <> '' AND AttributeValue12 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName13] [AttributeName], [AttributeValue13] [AttributeValue],13 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName13 <> '' AND AttributeValue13 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName14] [AttributeName], [AttributeValue14] [AttributeValue],14 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName14 <> '' AND AttributeValue14 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName15] [AttributeName], [AttributeValue15] [AttributeValue],15 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName15 <> '' AND AttributeValue15 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName16] [AttributeName], [AttributeValue16] [AttributeValue],16 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName16 <> '' AND AttributeValue16 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName17] [AttributeName], [AttributeValue17] [AttributeValue],17 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName17 <> '' AND AttributeValue17 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName18] [AttributeName], [AttributeValue18] [AttributeValue],18 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName18 <> '' AND AttributeValue18 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName19] [AttributeName], [AttributeValue19] [AttributeValue],19 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName19 <> '' AND AttributeValue19 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName20] [AttributeName], [AttributeValue20] [AttributeValue],20 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName20 <> '' AND AttributeValue20 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName21] [AttributeName], [AttributeValue21] [AttributeValue],21 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName21 <> '' AND AttributeValue21 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName22] [AttributeName], [AttributeValue22] [AttributeValue],22 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName22 <> '' AND AttributeValue22 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName23] [AttributeName], [AttributeValue23] [AttributeValue],23 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName23 <> '' AND AttributeValue23 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName24] [AttributeName], [AttributeValue24] [AttributeValue],24 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName24 <> '' AND AttributeValue24 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName25] [AttributeName], [AttributeValue25] [AttributeValue],25 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName25 <> '' AND AttributeValue25 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName26] [AttributeName], [AttributeValue26] [AttributeValue],26 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName26 <> '' AND AttributeValue26 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName27] [AttributeName], [AttributeValue27] [AttributeValue],27 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName27 <> '' AND AttributeValue27 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName28] [AttributeName], [AttributeValue28] [AttributeValue],28 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName28 <> '' AND AttributeValue28 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName29] [AttributeName], [AttributeValue29] [AttributeValue],29 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName29 <> '' AND AttributeValue29 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName30] [AttributeName], [AttributeValue30] [AttributeValue],30 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName30 <> '' AND AttributeValue30 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName31] [AttributeName], [AttributeValue31] [AttributeValue],31 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName31 <> '' AND AttributeValue31 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName32] [AttributeName], [AttributeValue32] [AttributeValue],32 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName32 <> '' AND AttributeValue32 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName33] [AttributeName], [AttributeValue33] [AttributeValue],33 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName33 <> '' AND AttributeValue33 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName34] [AttributeName], [AttributeValue34] [AttributeValue],34 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName34 <> '' AND AttributeValue34 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName35] [AttributeName], [AttributeValue35] [AttributeValue],35 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName35 <> '' AND AttributeValue35 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName36] [AttributeName], [AttributeValue36] [AttributeValue],36 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName36 <> '' AND AttributeValue36 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName37] [AttributeName], [AttributeValue37] [AttributeValue],37 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName37 <> '' AND AttributeValue37 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName38] [AttributeName], [AttributeValue38] [AttributeValue],38 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName38 <> '' AND AttributeValue38 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName39] [AttributeName], [AttributeValue39] [AttributeValue],39 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName39 <> '' AND AttributeValue39 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName40] [AttributeName], [AttributeValue40] [AttributeValue],40 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName40 <> '' AND AttributeValue40 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName41] [AttributeName], [AttributeValue41] [AttributeValue],41 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName41 <> '' AND AttributeValue41 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName42] [AttributeName], [AttributeValue42] [AttributeValue],42 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName42 <> '' AND AttributeValue42 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName43] [AttributeName], [AttributeValue43] [AttributeValue],43 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName43 <> '' AND AttributeValue43 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName44] [AttributeName], [AttributeValue44] [AttributeValue],44 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName44 <> '' AND AttributeValue44 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName45] [AttributeName], [AttributeValue45] [AttributeValue],45 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName45 <> '' AND AttributeValue45 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName46] [AttributeName], [AttributeValue46] [AttributeValue],46 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName46 <> '' AND AttributeValue46 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName47] [AttributeName], [AttributeValue47] [AttributeValue],47 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName47 <> '' AND AttributeValue47 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName48] [AttributeName], [AttributeValue48] [AttributeValue],48 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName48 <> '' AND AttributeValue48 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName49] [AttributeName], [AttributeValue49] [AttributeValue],49 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName49 <> '' AND AttributeValue49 <> ''
		UNION SELECT [CustomerItemID] ProductName, [AttributeName50] [AttributeName], [AttributeValue50] [AttributeValue],50 SortOrder FROM dbo.TradeServicesProduct s WHERE AttributeName50 <> '' AND AttributeValue50 <> ''
		UNION SELECT [CustomerItemID] ProductName, 'Brand'			 [AttributeName], ISNULL(BrandName,'')	 [AttributeValue],-1 SortOrder FROM dbo.TradeServicesProduct s