
CREATE VIEW [dbo].[vw_QualifyingInvoices] AS
	SELECT DISTINCT
		ETLSourceID,
		BillToNo,
		-- When Bill to and Ship To are the same number, they are the "ship to bill to" client which has a blank customer number,
		-- Need this everywhere, so fix here,
		CASE WHEN ISNULL(ShipToNo,'') = BillToNo THEN '' ELSE ISNULL(ShipToNo,'') END ShipToNo,
		UPPER(ERPOrderNo) ERPOrderNo,
		Gen,
		GenID,
		CustomerPONo,
		OrderDate,
		OrderStatus,
		OrderType,
		OrderedBy,
		BillToName,
		BillToAddressLine1,
		BillToAddressLine2,
		BillToAddressCity,
		BillToAddressState,
		BillToAddressPostalCode,
		ShipToName,
		ShipToAddressLine1,
		ShipToAddressLine2,
		ShipToCity,
		ShipToState,
		ShipToPostalCode,
		ShipViaID,
		TermsCode,
		OrderSubTotal,
		TotalDiscount,
		TotalFreightAndHandling,
		FreightIn,
		FreightOut,
		HandlingIn,
		HandlingOut,
		ExpFreightIn,
		ExpFreightOut,
		ExpHandlingIn,
		ExpHandlingOut,
		SalesTax1,
		SalesTax2,
		SalesTax3,
		SalesTax1 + SalesTax2 + SalesTax3 as TotalTax,
		OrderTotalAmount,
		InsideSalesPersonID,
		OutsideSalesPersonID,
  		ShipBranch,
		ShipDate,
		ShipVia
	FROM DM_ECommerce..vw_InvoicedLedgerHeaders
	WHERE OrderDate >= CAST(
							CAST(DATEPART(YEAR, GETDATE()) - 2 AS VARCHAR(4))
							+ '-' + CAST(DATEPART(MONTH, GETDATE()) AS VARCHAR(2))
							+ '-01' AS DATETIME)