CREATE TABLE [dbo].[Category] (
    [Id]                UNIQUEIDENTIFIER DEFAULT (newsequentialid()) NULL,
    [ParentId]          UNIQUEIDENTIFIER NULL,
    [WebSiteId]         UNIQUEIDENTIFIER NOT NULL,
    [Name]              NVARCHAR (255)   NOT NULL,
    [ShortDescription]  NVARCHAR (255)   DEFAULT ('') NOT NULL,
    [SmallImagePath]    NVARCHAR (1024)  DEFAULT ('') NOT NULL,
    [LargeImagePath]    NVARCHAR (1024)  DEFAULT ('') NOT NULL,
    [ActivateOn]        DATETIME2 (7)    DEFAULT (getdate()) NOT NULL,
    [DeactivateOn]      DATETIME2 (7)    NULL,
    [UrlSegment]        NVARCHAR (255)   DEFAULT ('') NOT NULL,
    [MetaKeywords]      NVARCHAR (MAX)   DEFAULT ('') NOT NULL,
    [MetaDescription]   NVARCHAR (MAX)   DEFAULT ('') NOT NULL,
    [SortOrder]         INT              DEFAULT ((0)) NOT NULL,
    [ShowDetail]        BIT              DEFAULT ((1)) NOT NULL,
    [PageTitle]         NVARCHAR (1024)  DEFAULT ('') NOT NULL,
    [ContentManagerId]  UNIQUEIDENTIFIER NULL,
    [DocumentManagerId] UNIQUEIDENTIFIER NULL,
    [ERPProductValues]  NVARCHAR (MAX)   DEFAULT ('') NOT NULL,
    [IsFeatured]        BIT              DEFAULT ((0)) NOT NULL,
    [IsDynamic]         BIT              DEFAULT ((0)) NOT NULL,
    [RuleManagerId]     UNIQUEIDENTIFIER DEFAULT (NULL) NULL,
    [ImageAltText]      NVARCHAR (1024)  DEFAULT ('') NOT NULL,
    [CreatedOn]         DATETIME2 (7)    DEFAULT (getdate()) NOT NULL,
    [CreatedBy]         NVARCHAR (100)   DEFAULT ('') NOT NULL,
    [ModifiedOn]        DATETIME2 (7)    DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]        NVARCHAR (100)   DEFAULT ('') NOT NULL,
    [Path]              NVARCHAR (1024)  DEFAULT ('') NOT NULL,
    [ParentPath]        NVARCHAR (1024)  DEFAULT ('') NOT NULL
);

