CREATE TABLE [dbo].[ConsolidatedFile] (
    [TS_ID]                                     NVARCHAR (255)  NULL,
    [CUSTOMER_Item ID]                          NVARCHAR (255)  NULL,
    [CUSTOMER_Manufacturer Name]                NVARCHAR (255)  NULL,
    [CUSTOMER_Manufacturer Part Number]         NVARCHAR (255)  NULL,
    [CUSTOMER_Description]                      NVARCHAR (255)  NULL,
    [CUSTOMER_UPC]                              NVARCHAR (255)  NULL,
    [CUSTOMER_Price Line]                       NVARCHAR (255)  NULL,
    [CUSTOMER_P C]                              NVARCHAR (255)  NULL,
    [CUSTOMER_Status]                           NVARCHAR (255)  NULL,
    [CUSTOMER_Sell Group]                       NVARCHAR (255)  NULL,
    [COMMODITY GENERIC (Yes or No)]             NVARCHAR (255)  NULL,
    [MANUFACTURER NAME]                         NVARCHAR (255)  NULL,
    [MANUFACTURER PART NUMBER]                  NVARCHAR (255)  NULL,
    [ADDITIONAL PART NUMBER (TS)]               NVARCHAR (255)  NULL,
    [SHORT DESCRIPTION (Morsco Format)]         NVARCHAR (255)  NULL,
    [PRODUCT NAME]                              NVARCHAR (255)  NULL,
    [BRAND NAME]                                NVARCHAR (255)  NULL,
    [SERIES MODEL FIGURE NUMBER]                NVARCHAR (255)  NULL,
    [UPC (w check Digit)]                       NVARCHAR (255)  NULL,
    [UNSPSC]                                    NVARCHAR (255)  NULL,
    [TS COMMODITY LEVEL 1]                      NVARCHAR (255)  NULL,
    [TS COMMODITY LEVEL 2]                      NVARCHAR (255)  NULL,
    [TS COMMODITY LEVEL 3]                      NVARCHAR (255)  NULL,
    [TS COMMODITY LEVEL 4]                      NVARCHAR (255)  NULL,
    [TS COMMODITY LEVEL 5]                      NVARCHAR (255)  NULL,
    [TS SCHEMA PARENT CLASS NAME]               NVARCHAR (255)  NULL,
    [TS SCHEMA LEAF CLASS NAME]                 NVARCHAR (255)  NULL,
    [Attribute Name_1]                          NVARCHAR (255)  NULL,
    [Attribute Value_1]                         NVARCHAR (255)  NULL,
    [Attribute Name_2]                          NVARCHAR (255)  NULL,
    [Attribute Value_2]                         NVARCHAR (255)  NULL,
    [Attribute Name_3]                          NVARCHAR (255)  NULL,
    [Attribute Value_3]                         NVARCHAR (255)  NULL,
    [Attribute Name_4]                          NVARCHAR (255)  NULL,
    [Attribute Value_4]                         NVARCHAR (255)  NULL,
    [Attribute Name_5]                          NVARCHAR (255)  NULL,
    [Attribute Value_5]                         NVARCHAR (255)  NULL,
    [Attribute Name_6]                          NVARCHAR (255)  NULL,
    [Attribute Value_6]                         NVARCHAR (255)  NULL,
    [Attribute Name_7]                          NVARCHAR (255)  NULL,
    [Attribute Value_7]                         NVARCHAR (255)  NULL,
    [Attribute Name_8]                          NVARCHAR (255)  NULL,
    [Attribute Value_8]                         NVARCHAR (1500) NULL,
    [Attribute Name_9]                          NVARCHAR (255)  NULL,
    [Attribute Value_9]                         NVARCHAR (255)  NULL,
    [Attribute Name_10]                         NVARCHAR (255)  NULL,
    [Attribute Value_10]                        NVARCHAR (255)  NULL,
    [Attribute Name_11]                         NVARCHAR (255)  NULL,
    [Attribute Value_11]                        NVARCHAR (255)  NULL,
    [Attribute Name_12]                         NVARCHAR (255)  NULL,
    [Attribute Value_12]                        NVARCHAR (255)  NULL,
    [Attribute Name_13]                         NVARCHAR (255)  NULL,
    [Attribute Value_13]                        NVARCHAR (255)  NULL,
    [Attribute Name_14]                         NVARCHAR (255)  NULL,
    [Attribute Value_14]                        NVARCHAR (255)  NULL,
    [Attribute Name_15]                         NVARCHAR (255)  NULL,
    [Attribute Value_15]                        NVARCHAR (255)  NULL,
    [Attribute Name_16]                         NVARCHAR (255)  NULL,
    [Attribute Value_16]                        NVARCHAR (255)  NULL,
    [Attribute Name_17]                         NVARCHAR (255)  NULL,
    [Attribute Value_17]                        NVARCHAR (255)  NULL,
    [Attribute Name_18]                         NVARCHAR (255)  NULL,
    [Attribute Value_18]                        NVARCHAR (255)  NULL,
    [Attribute Name_19]                         NVARCHAR (255)  NULL,
    [Attribute Value_19]                        NVARCHAR (255)  NULL,
    [Attribute Name_20]                         NVARCHAR (255)  NULL,
    [Attribute Value_20]                        NVARCHAR (255)  NULL,
    [Attribute Name_21]                         NVARCHAR (255)  NULL,
    [Attribute Value_21]                        NVARCHAR (255)  NULL,
    [Attribute Name_22]                         NVARCHAR (255)  NULL,
    [Attribute Value_22]                        NVARCHAR (255)  NULL,
    [Attribute Name_23]                         NVARCHAR (255)  NULL,
    [Attribute Value_23]                        NVARCHAR (255)  NULL,
    [Attribute Name_24]                         NVARCHAR (255)  NULL,
    [Attribute Value_24]                        NVARCHAR (255)  NULL,
    [Attribute Name_25]                         NVARCHAR (255)  NULL,
    [Attribute Value_25]                        NVARCHAR (255)  NULL,
    [Attribute Name_26]                         NVARCHAR (255)  NULL,
    [Attribute Value_26]                        NVARCHAR (255)  NULL,
    [Attribute Name_27]                         NVARCHAR (255)  NULL,
    [Attribute Value_27]                        NVARCHAR (255)  NULL,
    [Attribute Name_28]                         NVARCHAR (255)  NULL,
    [Attribute Value_28]                        NVARCHAR (255)  NULL,
    [Attribute Name_29]                         NVARCHAR (255)  NULL,
    [Attribute Value_29]                        NVARCHAR (255)  NULL,
    [Attribute Name_30]                         NVARCHAR (255)  NULL,
    [Attribute Value_30]                        NVARCHAR (255)  NULL,
    [Attribute Name_31]                         NVARCHAR (255)  NULL,
    [Attribute Value_31]                        NVARCHAR (255)  NULL,
    [Attribute Name_32]                         NVARCHAR (255)  NULL,
    [Attribute Value_32]                        NVARCHAR (255)  NULL,
    [Attribute Name_33]                         NVARCHAR (255)  NULL,
    [Attribute Value_33]                        NVARCHAR (255)  NULL,
    [Attribute Name_34]                         NVARCHAR (255)  NULL,
    [Attribute Value_34]                        NVARCHAR (255)  NULL,
    [Attribute Name_35]                         NVARCHAR (255)  NULL,
    [Attribute Value_35]                        NVARCHAR (255)  NULL,
    [Attribute Name_36]                         NVARCHAR (255)  NULL,
    [Attribute Value_36]                        NVARCHAR (255)  NULL,
    [Attribute Name_37]                         NVARCHAR (255)  NULL,
    [Attribute Value_37]                        NVARCHAR (255)  NULL,
    [Attribute Name_38]                         NVARCHAR (255)  NULL,
    [Attribute Value_38]                        NVARCHAR (255)  NULL,
    [Attribute Name_39]                         NVARCHAR (255)  NULL,
    [Attribute Value_39]                        NVARCHAR (255)  NULL,
    [Attribute Name_40]                         NVARCHAR (255)  NULL,
    [Attribute Value_40]                        NVARCHAR (255)  NULL,
    [Attribute Name_41]                         NVARCHAR (255)  NULL,
    [Attribute Value_41]                        NVARCHAR (255)  NULL,
    [Attribute Name_42]                         NVARCHAR (255)  NULL,
    [Attribute Value_42]                        NVARCHAR (255)  NULL,
    [Attribute Name_43]                         NVARCHAR (255)  NULL,
    [Attribute Value_43]                        NVARCHAR (255)  NULL,
    [Attribute Name_44]                         NVARCHAR (255)  NULL,
    [Attribute Value_44]                        NVARCHAR (255)  NULL,
    [Attribute Name_45]                         NVARCHAR (255)  NULL,
    [Attribute Value_45]                        NVARCHAR (255)  NULL,
    [Attribute Name_46]                         NVARCHAR (255)  NULL,
    [Attribute Value_46]                        NVARCHAR (255)  NULL,
    [Attribute Name_47]                         NVARCHAR (255)  NULL,
    [Attribute Value_47]                        NVARCHAR (255)  NULL,
    [Attribute Name_48]                         NVARCHAR (255)  NULL,
    [Attribute Value_48]                        NVARCHAR (255)  NULL,
    [Attribute Name_49]                         NVARCHAR (255)  NULL,
    [Attribute Value_49]                        NVARCHAR (255)  NULL,
    [Attribute Name_50]                         NVARCHAR (255)  NULL,
    [Attribute Value_50]                        NVARCHAR (255)  NULL,
    [ADDITIONAL INFORMATION]                    NVARCHAR (255)  NULL,
    [LONG DESCRIPTION]                          VARCHAR (2500)  NULL,
    [FEATURES BENEFITS]                         VARCHAR (2500)  NULL,
    [ITEM WEIGHT (pounds)]                      NVARCHAR (255)  NULL,
    [PACKAGE WEIGHT (pounds)]                   NVARCHAR (255)  NULL,
    [PACKAGE WIDTH (inch)]                      NVARCHAR (255)  NULL,
    [PACKAGE LENGTH (inch)]                     NVARCHAR (255)  NULL,
    [PACKAGE HEIGHT (inch)]                     NVARCHAR (255)  NULL,
    [PACKAGE VOLUME (cubic inch)]               NVARCHAR (255)  NULL,
    [COUNTRY of ORIGIN]                         NVARCHAR (255)  NULL,
    [LEAD FREE (Yes or No)]                     NVARCHAR (255)  NULL,
    [MERCURY FREE (Yes or No)]                  NVARCHAR (255)  NULL,
    [WATER SENSE SAVER (Yes or No)]             NVARCHAR (255)  NULL,
    [ENERGY STAR RATED (Yes or No)]             NVARCHAR (255)  NULL,
    [HAZARDOUS MATERIAL (Yes or No)]            NVARCHAR (255)  NULL,
    [IMAGE URL_Large (600 x 600)]               VARCHAR (1024)  NULL,
    [IMAGE NAME_Large (600 x 600)]              NVARCHAR (255)  NULL,
    [IMAGE URL_Medium (145 x 145)]              VARCHAR (1024)  NULL,
    [IMAGE NAME_Medium (145 x 145)]             NVARCHAR (255)  NULL,
    [IMAGE URL_Small (75 x 75)]                 VARCHAR (1024)  NULL,
    [IMAGE NAME_Small (75 x 75)]                NVARCHAR (255)  NULL,
    [MFR CATALOG DOCUMENT]                      VARCHAR (1024)  NULL,
    [MFR CATALOG DOCUMENT NAME]                 NVARCHAR (255)  NULL,
    [MFR SPECIFICATION TECHNICAL DOCUMENT]      VARCHAR (1024)  NULL,
    [MFR SPECIFICATION TECHNICAL DOCUMENT NAME] NVARCHAR (255)  NULL,
    [MFR ITEM DATA DOCUMENT]                    VARCHAR (1024)  NULL,
    [MFR ITEM DATA DOCUMENT NAME]               NVARCHAR (255)  NULL,
    [MFR MSDS DOCUMENT]                         VARCHAR (1024)  NULL,
    [MFR MSDS DOCUMENT NAME]                    NVARCHAR (255)  NULL,
    [MFR INSTALLATION OPERATOR DOCUMENT]        VARCHAR (1024)  NULL,
    [MFR INSTALLATION OPERATOR DOCUMENT NAME]   NVARCHAR (255)  NULL,
    [TS_STATUS]                                 VARCHAR (50)    NULL,
    [TS_COMMENTS for CUSTOMER]                  VARCHAR (1500)  NULL,
    [ADDITIONAL URL_1 (Mfr Item Page)]          VARCHAR (1024)  NULL,
    [ADDITIONAL URL_2]                          VARCHAR (1024)  NULL
);

