CREATE TABLE [dbo].[Customer] (
    [Id]                        UNIQUEIDENTIFIER CONSTRAINT [DF_Customer_CustomerId] DEFAULT (newsequentialid()) NOT NULL,
    [ParentId]                  UNIQUEIDENTIFIER NULL,
    [CustomerNumber]            NVARCHAR (50)    CONSTRAINT [DF_Customer_CustomerNumber] DEFAULT ('') NOT NULL,
    [CustomerSequence]          NVARCHAR (50)    CONSTRAINT [DF_Customer_CustomerSequence] DEFAULT ('') NOT NULL,
    [CustomerType]              NVARCHAR (50)    CONSTRAINT [DF_Customer_CustomerType] DEFAULT ('') NOT NULL,
    [CompanyName]               NVARCHAR (100)   CONSTRAINT [DF_Customer_Company] DEFAULT ('') NOT NULL,
    [ContactFullName]           NVARCHAR (100)   CONSTRAINT [DF_Customer_Contact] DEFAULT ('') NOT NULL,
    [FirstName]                 NVARCHAR (100)   CONSTRAINT [DF_Customer_FirstName] DEFAULT ('') NOT NULL,
    [MiddleName]                NVARCHAR (100)   CONSTRAINT [DF_Customer_MiddleName] DEFAULT ('') NOT NULL,
    [LastName]                  NVARCHAR (100)   CONSTRAINT [DF_Customer_LastName] DEFAULT ('') NOT NULL,
    [Phone]                     NVARCHAR (50)    CONSTRAINT [DF_Customer_Phone1] DEFAULT ('') NOT NULL,
    [Fax]                       NVARCHAR (50)    CONSTRAINT [DF_Customer_Fax] DEFAULT ('') NOT NULL,
    [TermsCode]                 NVARCHAR (50)    CONSTRAINT [DF_Customer_TermsCode] DEFAULT ('') NOT NULL,
    [ShipCode]                  NVARCHAR (50)    CONSTRAINT [DF_Customer_ShipCode] DEFAULT ('') NOT NULL,
    [BankCode]                  NVARCHAR (50)    CONSTRAINT [DF_Customer_BankCode] DEFAULT ('') NOT NULL,
    [TaxCode1]                  NVARCHAR (50)    CONSTRAINT [DF_Customer_TaxCode1] DEFAULT ('') NOT NULL,
    [TaxCode2]                  NVARCHAR (50)    CONSTRAINT [DF_Customer_TaxCode2] DEFAULT ('') NOT NULL,
    [PriceCode]                 NVARCHAR (50)    CONSTRAINT [DF_Customer_PriceCode] DEFAULT ('') NOT NULL,
    [CurrencyCode]              NVARCHAR (50)    CONSTRAINT [DF_Customer_CurrencyCode] DEFAULT ('') NOT NULL,
    [EndUserType]               NVARCHAR (50)    CONSTRAINT [DF_Customer_EndUserType] DEFAULT ('') NOT NULL,
    [ShipSite]                  NVARCHAR (50)    CONSTRAINT [DF_Customer_ShipSite] DEFAULT ('') NOT NULL,
    [ShipEarly]                 BIT              CONSTRAINT [DF_Customer_ShipEarly] DEFAULT ((1)) NOT NULL,
    [ShipPartial]               BIT              CONSTRAINT [DF_Customer_ShipPartial] DEFAULT ((1)) NOT NULL,
    [Address1]                  NVARCHAR (100)   CONSTRAINT [DF_Customer_Address1] DEFAULT ('') NOT NULL,
    [Address2]                  NVARCHAR (100)   CONSTRAINT [DF_Customer_Address2] DEFAULT ('') NOT NULL,
    [Address3]                  NVARCHAR (100)   CONSTRAINT [DF_Customer_Address3] DEFAULT ('') NOT NULL,
    [Address4]                  NVARCHAR (100)   CONSTRAINT [DF_Customer_Address4] DEFAULT ('') NOT NULL,
    [City]                      NVARCHAR (100)   CONSTRAINT [DF_Customer_City] DEFAULT ('') NOT NULL,
    [State]                     NVARCHAR (50)    CONSTRAINT [DF_Customer_State] DEFAULT ('') NOT NULL,
    [PostalCode]                NVARCHAR (50)    CONSTRAINT [DF_Customer_Zip] DEFAULT ('') NOT NULL,
    [Country]                   NVARCHAR (100)   CONSTRAINT [DF_Customer_Country] DEFAULT ('') NOT NULL,
    [CreditHold]                BIT              CONSTRAINT [DF_Customer_CreditHold] DEFAULT ((0)) NOT NULL,
    [CreditLimit]               DECIMAL (18, 5)  CONSTRAINT [DF_Customer_CreditLimit] DEFAULT ((0)) NOT NULL,
    [Email]                     NVARCHAR (256)   CONSTRAINT [DF_Customer_ShipToEmail] DEFAULT ('') NOT NULL,
    [Distance]                  DECIMAL (18, 5)  CONSTRAINT [DF_Customer_Distance] DEFAULT ((0.00)) NOT NULL,
    [DiscountPercent]           DECIMAL (18, 5)  CONSTRAINT [DF_Customer_Discount] DEFAULT ((0)) NOT NULL,
    [SendEmail]                 BIT              CONSTRAINT [DF_Customer_SendEmail] DEFAULT ((0)) NOT NULL,
    [LogoImagePath]             NVARCHAR (1024)  CONSTRAINT [DF_Customer_Image] DEFAULT ('') NOT NULL,
    [IsActive]                  BIT              CONSTRAINT [DF_Customer_Active] DEFAULT ((1)) NOT NULL,
    [AllowDropShip]             BIT              CONSTRAINT [DF_Customer_AllowDropShip] DEFAULT ((0)) NOT NULL,
    [DropShipFeeRequired]       BIT              CONSTRAINT [DF_Customer_DropShipFeeRequired] DEFAULT ((0)) NOT NULL,
    [IsDropShip]                BIT              CONSTRAINT [DF_Customer_IsDropShip] DEFAULT ((0)) NOT NULL,
    [StateId]                   UNIQUEIDENTIFIER NULL,
    [CountryId]                 UNIQUEIDENTIFIER NULL,
    [IsGuest]                   BIT              CONSTRAINT [DF_Customer_IsGuest] DEFAULT ((0)) NOT NULL,
    [ERPNumber]                 NVARCHAR (50)    CONSTRAINT [DF_Customer_ERPNumber] DEFAULT ('') NOT NULL,
    [Territory]                 NVARCHAR (100)   CONSTRAINT [DF_Customer_Territory] DEFAULT ('') NOT NULL,
    [CustomLandingPage]         NVARCHAR (1024)  CONSTRAINT [DF_Customer_CustomLandingPage] DEFAULT ('') NULL,
    [BudgetEnforcementLevel]    NVARCHAR (50)    CONSTRAINT [DF_Customer_BudgetEnforcementLevel] DEFAULT ('None') NOT NULL,
    [CostCodeDescription]       NVARCHAR (100)   CONSTRAINT [DF_Customer_CostCodeDescription] DEFAULT ('') NOT NULL,
    [DefaultCostCode]           NVARCHAR (100)   CONSTRAINT [DF_Customer_DefaultCostCode] DEFAULT ('') NOT NULL,
    [IgnoreProductRestrictions] BIT              CONSTRAINT [DF_CustomerUserProfile_IgnoreProductRestrictions] DEFAULT ((0)) NOT NULL,
    [ERPSequence]               NVARCHAR (50)    CONSTRAINT [DF_Customer_ERPSequence] DEFAULT ('') NOT NULL,
    [PricingCustomerId]         UNIQUEIDENTIFIER NULL,
    [ModifedOn]                 DATETIME2 (7)    CONSTRAINT [DF_Customer_ModifyDate] DEFAULT (getdate()) NOT NULL,
    [CurrencyId]                UNIQUEIDENTIFIER NULL,
    [PrimarySalespersonId]      UNIQUEIDENTIFIER NULL,
    [IsBillTo]                  BIT              CONSTRAINT [DF_Customer_IsBillTo] DEFAULT ((1)) NOT NULL,
    [IsShipTo]                  BIT              CONSTRAINT [DF_Customer_IsShipTo] DEFAULT ((1)) NOT NULL,
    [IsSoldTo]                  BIT              CONSTRAINT [DF_Customer_IsSoldTo] DEFAULT ((1)) NOT NULL,
    [DefaultWarehouseId]        UNIQUEIDENTIFIER NULL,
    [CreatedOn]                 DATETIME2 (7)    CONSTRAINT [DF_Customer_CreatedOn] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                 NVARCHAR (100)   CONSTRAINT [DF_Customer_CreatedBy] DEFAULT ('') NOT NULL,
    [ModifiedOn]                DATETIME2 (7)    CONSTRAINT [DF_Customer_ModifiedOn] DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]                NVARCHAR (100)   CONSTRAINT [DF_Customer_ModifiedBy] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED ([Id] ASC)
);

