CREATE TABLE [dbo].[InvoiceHistory] (
    [Id]                  UNIQUEIDENTIFIER CONSTRAINT [DF_InvoiceHistory_InvoiceHistoryId] DEFAULT (newsequentialid()) NOT NULL,
    [InvoiceNumber]       NVARCHAR (50)    CONSTRAINT [DF_InvoiceHistory_InvoiceNumber] DEFAULT ('') NOT NULL,
    [InvoiceDate]         DATETIME2 (7)    CONSTRAINT [DF_InvoiceHistory_InvoiceDate] DEFAULT (getdate()) NOT NULL,
    [DueDate]             DATETIME2 (7)    CONSTRAINT [DF_InvoiceHistory_DueDate] DEFAULT (getdate()) NOT NULL,
    [InvoiceType]         NVARCHAR (50)    CONSTRAINT [DF_InvoiceHistory_InvoiceType] DEFAULT ('') NOT NULL,
    [CustomerNumber]      NVARCHAR (50)    CONSTRAINT [DF_InvoiceHistory_CustomerNumber] DEFAULT ('') NOT NULL,
    [CustomerSequence]    NVARCHAR (50)    CONSTRAINT [DF_InvoiceHistory_CustomerSequence] DEFAULT ('') NOT NULL,
    [CustomerPO]          NVARCHAR (50)    CONSTRAINT [DF_InvoiceHistory_CustomerPO] DEFAULT ('') NOT NULL,
    [Status]              NVARCHAR (50)    CONSTRAINT [DF_InvoiceHistory_Status] DEFAULT ('') NOT NULL,
    [IsOpen]              BIT              CONSTRAINT [DF_InvoiceHistory_IsOpen] DEFAULT ((0)) NOT NULL,
    [CurrencyCode]        NVARCHAR (50)    CONSTRAINT [DF_InvoiceHistory_CurrencyCode] DEFAULT ('') NOT NULL,
    [Terms]               NVARCHAR (50)    CONSTRAINT [DF_InvoiceHistory_Terms] DEFAULT ('') NOT NULL,
    [ShipCode]            NVARCHAR (50)    CONSTRAINT [DF_InvoiceHistory_ShipCode] DEFAULT ('') NOT NULL,
    [Salesperson]         NVARCHAR (50)    CONSTRAINT [DF_InvoiceHistory_Salesperson] DEFAULT ('') NOT NULL,
    [BTCompanyName]       NVARCHAR (100)   CONSTRAINT [DF_InvoiceHistory_BTCompanyName] DEFAULT ('') NOT NULL,
    [BTAddress1]          NVARCHAR (100)   CONSTRAINT [DF_InvoiceHistory_BTAddress1] DEFAULT ('') NOT NULL,
    [BTAddress2]          NVARCHAR (100)   CONSTRAINT [DF_InvoiceHistory_BTAddress2] DEFAULT ('') NOT NULL,
    [BTCity]              NVARCHAR (100)   CONSTRAINT [DF_InvoiceHistory_BTCity] DEFAULT ('') NOT NULL,
    [BTState]             NVARCHAR (50)    CONSTRAINT [DF_InvoiceHistory_BTState] DEFAULT ('') NOT NULL,
    [BTPostalCode]        NVARCHAR (50)    CONSTRAINT [DF_InvoiceHistory_BTPostalCode] DEFAULT ('') NOT NULL,
    [BTCountry]           NVARCHAR (100)   CONSTRAINT [DF_InvoiceHistory_BTCountry] DEFAULT ('') NOT NULL,
    [STCompanyName]       NVARCHAR (100)   CONSTRAINT [DF_InvoiceHistory_STCompanyName] DEFAULT ('') NOT NULL,
    [STAddress1]          NVARCHAR (100)   CONSTRAINT [DF_InvoiceHistory_STAddress1] DEFAULT ('') NOT NULL,
    [STAddress2]          NVARCHAR (100)   CONSTRAINT [DF_InvoiceHistory_STAddress2] DEFAULT ('') NOT NULL,
    [STCity]              NVARCHAR (100)   CONSTRAINT [DF_InvoiceHistory_STCity] DEFAULT ('') NOT NULL,
    [STState]             NVARCHAR (50)    CONSTRAINT [DF_InvoiceHistory_STState] DEFAULT ('') NOT NULL,
    [STPostalCode]        NVARCHAR (50)    CONSTRAINT [DF_InvoiceHistory_STPostalCode] DEFAULT ('') NOT NULL,
    [STCountry]           NVARCHAR (100)   CONSTRAINT [DF_InvoiceHistory_STCountry] DEFAULT ('') NOT NULL,
    [Notes]               NVARCHAR (MAX)   CONSTRAINT [DF_InvoiceHistory_Notes] DEFAULT ('') NOT NULL,
    [ProductTotal]        DECIMAL (18, 5)  CONSTRAINT [DF_InvoiceHistory_ProductTotal] DEFAULT ((0)) NOT NULL,
    [DiscountAmount]      DECIMAL (18, 5)  CONSTRAINT [DF_InvoiceHistory_DiscountAmount] DEFAULT ((0)) NOT NULL,
    [ShippingAndHandling] DECIMAL (18, 5)  CONSTRAINT [DF_InvoiceHistory_ShippingAndHandling] DEFAULT ((0)) NOT NULL,
    [OtherCharges]        DECIMAL (18, 5)  CONSTRAINT [DF_InvoiceHistory_OtherCharges] DEFAULT ((0)) NOT NULL,
    [TaxAmount]           DECIMAL (18, 5)  CONSTRAINT [DF_InvoiceHistory_TaxAmount] DEFAULT ((0)) NOT NULL,
    [InvoiceTotal]        DECIMAL (18, 5)  CONSTRAINT [DF_InvoiceHistory_InvoiceTotal] DEFAULT ((0)) NOT NULL,
    [CurrentBalance]      DECIMAL (18, 5)  CONSTRAINT [DF_InvoiceHistory_CurrentBalance] DEFAULT ((0)) NOT NULL,
    [CreatedOn]           DATETIME2 (7)    CONSTRAINT [DF_InvoiceHistory_CreatedOn] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]           NVARCHAR (100)   CONSTRAINT [DF_InvoiceHistory_CreatedBy] DEFAULT ('') NOT NULL,
    [ModifiedOn]          DATETIME2 (7)    CONSTRAINT [DF_InvoiceHistory_ModifiedOn] DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]          NVARCHAR (100)   CONSTRAINT [DF_InvoiceHistory_ModifiedBy] DEFAULT ('') NOT NULL,
    [EclipseID]           NVARCHAR (50)    NULL,
    [GenerationID]        NVARCHAR (10)    NULL,
    CONSTRAINT [PK_InvoiceHistory] PRIMARY KEY CLUSTERED ([Id] ASC)
);

