CREATE TABLE [dbo].[OrderHistoryLine] (
    [Id]                     UNIQUEIDENTIFIER CONSTRAINT [DF_OrderHistoryLine_OrderHistoryLineId] DEFAULT (newsequentialid()) NOT NULL,
    [OrderHistoryId]         UNIQUEIDENTIFIER NOT NULL,
    [RequiredDate]           DATETIME2 (7)    NULL,
    [LastShipDate]           DATETIME2 (7)    NULL,
    [CustomerNumber]         NVARCHAR (50)    CONSTRAINT [DF_OrderHistoryLine_CustomerNumber] DEFAULT ('') NOT NULL,
    [CustomerSequence]       NVARCHAR (50)    CONSTRAINT [DF_OrderHistoryLine_CustomerSequence] DEFAULT ('') NOT NULL,
    [LineType]               NVARCHAR (50)    CONSTRAINT [DF_OrderHistoryLine_LineType] DEFAULT ('') NOT NULL,
    [Status]                 NVARCHAR (50)    CONSTRAINT [DF_OrderHistoryLine_Status] DEFAULT ('') NOT NULL,
    [LineNumber]             DECIMAL (18, 5)  CONSTRAINT [DF_OrderHistoryLine_LineNumber] DEFAULT ((0)) NOT NULL,
    [ReleaseNumber]          DECIMAL (18, 5)  CONSTRAINT [DF_OrderHistoryLine_ReleaseNumber] DEFAULT ((0)) NOT NULL,
    [ProductERPNumber]       NVARCHAR (50)    CONSTRAINT [DF_OrderHistoryLine_ProductERPNumber] DEFAULT ('') NOT NULL,
    [CustomerProductNumber]  NVARCHAR (50)    CONSTRAINT [DF_OrderHistoryLine_CustomerProductNumber] DEFAULT ('') NOT NULL,
    [LinePOReference]        NVARCHAR (50)    CONSTRAINT [DF_OrderHistoryLine_LinePOReference] DEFAULT ('') NOT NULL,
    [Description]            NVARCHAR (2048)  CONSTRAINT [DF_OrderHistoryLine_Description] DEFAULT ('') NOT NULL,
    [Warehouse]              NVARCHAR (50)    CONSTRAINT [DF_OrderHistoryLine_Warehouse] DEFAULT ('') NOT NULL,
    [Notes]                  NVARCHAR (MAX)   CONSTRAINT [DF_OrderHistoryLine_Notes] DEFAULT ('') NOT NULL,
    [QtyOrdered]             DECIMAL (18, 5)  CONSTRAINT [DF_OrderHistoryLine_QtyOrdered] DEFAULT ((0)) NOT NULL,
    [QtyShipped]             DECIMAL (18, 5)  CONSTRAINT [DF_OrderHistoryLine_QtyShipped] DEFAULT ((0)) NOT NULL,
    [UnitOfMeasure]          NVARCHAR (50)    CONSTRAINT [DF_OrderHistoryLine_UnitOfMeasure] DEFAULT ('') NOT NULL,
    [InventoryQtyOrdered]    DECIMAL (18, 5)  CONSTRAINT [DF_OrderHistoryLine_InventoryQtyOrdered] DEFAULT ((0)) NOT NULL,
    [InventoryQtyShipped]    DECIMAL (18, 5)  CONSTRAINT [DF_OrderHistoryLine_InventoryQtyShipped] DEFAULT ((0)) NOT NULL,
    [UnitPrice]              DECIMAL (18, 5)  CONSTRAINT [DF_OrderHistoryLine_UnitPrice] DEFAULT ((0)) NOT NULL,
    [DiscountPercent]        DECIMAL (18, 5)  CONSTRAINT [DF_OrderHistoryLine_DiscountPercent] DEFAULT ((0)) NOT NULL,
    [DiscountAmount]         DECIMAL (18, 5)  CONSTRAINT [DF_OrderHistoryLine_DiscountAmount] DEFAULT ((0)) NOT NULL,
    [PromotionAmountApplied] DECIMAL (18, 5)  CONSTRAINT [DF_OrderHistoryLine_PromotionAmountApplied] DEFAULT ((0)) NOT NULL,
    [LineTotal]              DECIMAL (18, 5)  CONSTRAINT [DF_OrderHistoryLine_LineTotal] DEFAULT ((0)) NOT NULL,
    [RMAQtyRequested]        DECIMAL (18, 5)  NOT NULL,
    [RMAQtyReceived]         DECIMAL (18, 5)  NOT NULL,
    [CreatedOn]              DATETIME2 (7)    CONSTRAINT [DF_OrderHistoryLine_CreatedOn] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]              NVARCHAR (100)   CONSTRAINT [DF_OrderHistoryLine_CreatedBy] DEFAULT ('') NOT NULL,
    [ModifiedOn]             DATETIME2 (7)    CONSTRAINT [DF_OrderHistoryLine_ModifiedOn] DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]             NVARCHAR (100)   CONSTRAINT [DF_OrderHistoryLine_ModifiedBy] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_OrderHistoryLine] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_OrderHistoryLine_OrderHistory] FOREIGN KEY ([OrderHistoryId]) REFERENCES [dbo].[OrderHistory] ([Id]) ON DELETE CASCADE
);

