CREATE TABLE [dbo].[OrderHeaderLog] (
    [Id]                 UNIQUEIDENTIFIER CONSTRAINT [DF_OrderHeaderLog_Id] DEFAULT (newid()) NOT NULL,
    [ActivityInstanceId] UNIQUEIDENTIFIER NOT NULL,
    [OrderNo]            VARCHAR (512)    NOT NULL,
    [Generation]         VARCHAR (512)    NULL,
    [OrderStatus]        VARCHAR (512)    NULL,
    [InvoiceNo]          VARCHAR (512)    NULL,
    [InvoiceDate]        VARCHAR (512)    NULL,
    [OrderDate]          VARCHAR (512)    NULL,
    [RequireDate]        VARCHAR (512)    NULL,
    [ShipDate]           VARCHAR (512)    NULL,
    [BillToID]           VARCHAR (512)    NULL,
    [BillTo]             VARCHAR (512)    NULL,
    [ShipToID]           VARCHAR (512)    NULL,
    [ShipTo]             VARCHAR (512)    NULL,
    [ShippingAddress1]   VARCHAR (512)    NULL,
    [ShippingAddress2]   VARCHAR (512)    NULL,
    [City]               VARCHAR (512)    NULL,
    [State]              VARCHAR (512)    NULL,
    [Zip]                VARCHAR (512)    NULL,
    [Phone]              VARCHAR (512)    NULL,
    [PriceBranch]        VARCHAR (512)    NULL,
    [ShipBranch]         VARCHAR (512)    NULL,
    [CustomerPO]         VARCHAR (512)    NULL,
    [OrderBy]            VARCHAR (512)    NULL,
    [ReleaseNo]          VARCHAR (512)    NULL,
    [Salesperson]        VARCHAR (512)    NULL,
    [Writer]             VARCHAR (512)    NULL,
    [ShipVia]            VARCHAR (512)    NULL,
    [TaxJurisdiction]    VARCHAR (512)    NULL,
    [QuoteID]            VARCHAR (512)    NULL,
    [Terms]              VARCHAR (512)    NULL,
    [Freight]            VARCHAR (512)    NULL,
    [Handling]           VARCHAR (512)    NULL,
    [Tax]                VARCHAR (512)    NULL,
    [FET]                VARCHAR (512)    NULL,
    [ServiceChrg]        VARCHAR (512)    NULL,
    [Total]              VARCHAR (512)    NULL,
    [DueDate]            VARCHAR (512)    NULL,
    [CashDisc]           VARCHAR (512)    NULL,
    [WebDisc]            VARCHAR (512)    NULL,
    [DiscAmt]            VARCHAR (512)    NULL,
    [DiscDate]           VARCHAR (512)    NULL,
    [DiscTaken]          VARCHAR (512)    NULL,
    [Deposit]            VARCHAR (512)    NULL,
    [AmtPaid]            VARCHAR (512)    NULL,
    [ShippingInstr]      VARCHAR (1512)   NULL,
    [InternalNotes]      VARCHAR (1512)   NULL,
    [ShippingInstrLines] VARCHAR (1512)   NULL,
    [InternalNotesLines] VARCHAR (1512)   NULL,
    [LastUpdate]         VARCHAR (512)    NULL,
    [LastUpdateTime]     VARCHAR (512)    NULL,
    [LastUpdateUser]     VARCHAR (512)    NULL,
    [LastUpdateComments] VARCHAR (512)    NULL,
    [CreatedOn]          DATETIME2 (7)    NOT NULL,
    [CreatedBy]          VARCHAR (100)    NOT NULL,
    [ModifiedOn]         DATETIME2 (7)    NULL,
    [ModifiedBy]         VARCHAR (100)    NULL
);

