CREATE TABLE [dbo].[OrderHeader_Scrub] (
    [Id]                      UNIQUEIDENTIFIER DEFAULT (newsequentialid()) NOT NULL,
    [OrderNo]                 VARCHAR (10)     NULL,
    [Generation]              VARCHAR (4)      NULL,
    [PriceBranch]             VARCHAR (10)     NULL,
    [ShipBranch]              VARCHAR (10)     NULL,
    [OrderDate]               DATETIME         NULL,
    [RequireDate]             DATETIME         NULL,
    [ShipDate]                DATETIME         NULL,
    [InvoiceNo]               VARCHAR (12)     NULL,
    [InvoiceDate]             DATETIME         NULL,
    [OrderStatus]             VARCHAR (1)      NULL,
    [BillToID]                VARCHAR (10)     NULL,
    [BillTo]                  VARCHAR (50)     NULL,
    [ShipToID]                VARCHAR (10)     NULL,
    [ShipTo]                  VARCHAR (50)     NULL,
    [ShippingAddressName]     VARCHAR (75)     NULL,
    [ShippingAddressAddress]  VARCHAR (300)    NULL,
    [ShippingAddressCity]     VARCHAR (150)    NULL,
    [ShippingAddressState]    VARCHAR (10)     NULL,
    [ShippingAddressZip]      VARCHAR (15)     NULL,
    [ShippingAddressPhone]    VARCHAR (20)     NULL,
    [CustomerPO]              VARCHAR (15)     NULL,
    [OrderBy]                 VARCHAR (35)     NULL,
    [ReleaseNo]               VARCHAR (25)     NULL,
    [Salesperson]             VARCHAR (30)     NULL,
    [Writer]                  VARCHAR (30)     NULL,
    [ShipVia]                 VARCHAR (30)     NULL,
    [TaxJurisdiction]         VARCHAR (10)     NULL,
    [QuoteID]                 VARCHAR (15)     NULL,
    [Terms]                   VARCHAR (30)     NULL,
    [Freight]                 NUMERIC (18, 2)  NULL,
    [Handling]                NUMERIC (18, 2)  NULL,
    [Tax]                     NUMERIC (18, 2)  NULL,
    [FET]                     NUMERIC (18, 2)  NULL,
    [ServiceChrg]             NUMERIC (18, 2)  NULL,
    [Total]                   NUMERIC (18, 2)  NULL,
    [DueDate]                 DATETIME         NULL,
    [CashDisc]                NUMERIC (18, 2)  NULL,
    [WebDisc]                 NUMERIC (18, 2)  NULL,
    [DiscAmt]                 NUMERIC (18, 2)  NULL,
    [DiscDate]                DATETIME         NULL,
    [DiscTaken]               NUMERIC (18, 2)  NULL,
    [Deposit]                 NUMERIC (18, 2)  NULL,
    [AmtPaid]                 NUMERIC (18, 2)  NULL,
    [ShippingInstr]           VARCHAR (1000)   NULL,
    [InternalNotes]           VARCHAR (1000)   NULL,
    [ShippingInstrLines]      VARCHAR (1000)   NULL,
    [InternalNotesLines]      VARCHAR (1000)   NULL,
    [LastUpdateDate]          DATETIME         NULL,
    [LastUpdateTime]          DATETIME         NULL,
    [LastUpdateUser]          VARCHAR (20)     NULL,
    [LastUpdateComment]       VARCHAR (500)    NULL,
    [CreditCard]              VARCHAR (30)     NULL,
    [BidExpireDate]           DATETIME         NULL,
    [CreditCardCardType]      VARCHAR (10)     NULL,
    [CreditCardCardNumber]    VARCHAR (10)     NULL,
    [CreditCardExpireDate]    VARCHAR (6)      NULL,
    [CreditCardCardHolder]    VARCHAR (30)     NULL,
    [CreditCardStreetAddress] VARCHAR (150)    NULL,
    [CreditCardPostalCode]    VARCHAR (15)     NULL,
    [CreditCardCCVCode]       VARCHAR (30)     NULL,
    [CreditCardAuthType]      VARCHAR (1)      NULL,
    [CreditCardElementAcctID] VARCHAR (50)     NULL,
    [ShippingAddress]         VARCHAR (350)    NULL,
    [ActivityInstanceId]      UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_Scrub_OrderHeader] PRIMARY KEY CLUSTERED ([Id] ASC)
);

