CREATE TABLE [dbo].[OrderDetailLog] (
    [Id]                 UNIQUEIDENTIFIER NOT NULL,
    [OrderHeaderId]      UNIQUEIDENTIFIER NOT NULL,
    [ActivityInstanceId] UNIQUEIDENTIFIER NOT NULL,
    [OrderNo]            VARCHAR (512)    NULL,
    [Generation]         VARCHAR (512)    NULL,
    [ItemCode]           VARCHAR (512)    NULL,
    [Description]        VARCHAR (512)    NULL,
    [LineItemID]         VARCHAR (512)    NULL,
    [ProductID]          VARCHAR (512)    NULL,
    [PdwID]              VARCHAR (512)    NULL,
    [Desc_As_Stored]     VARCHAR (512)    NULL,
    [UPC]                VARCHAR (512)    NULL,
    [OrderQty]           VARCHAR (512)    NULL,
    [SellUnit]           VARCHAR (512)    NULL,
    [SellUnitQty]        VARCHAR (512)    NULL,
    [UnitPrice]          VARCHAR (512)    NULL,
    [ShipQty]            VARCHAR (512)    NULL,
    [ShipQtyAlpha]       VARCHAR (512)    NULL,
    [BaseShipQty]        VARCHAR (512)    NULL,
    [BaseUnit]           VARCHAR (512)    NULL,
    [ItemReleaseNo]      VARCHAR (512)    NULL,
    [SerialNumbers]      VARCHAR (512)    NULL,
    [CreatedOn]          DATETIME2 (7)    NOT NULL,
    [CreatedBy]          VARCHAR (100)    NOT NULL,
    [ModifiedOn]         DATETIME2 (7)    NULL,
    [ModifiedBy]         VARCHAR (100)    NULL
);

