CREATE TABLE [dbo].[Salesperson] (
    [Id]                 UNIQUEIDENTIFIER CONSTRAINT [DF_Salesperson_SalespersonId] DEFAULT (newsequentialid()) NOT NULL,
    [SalespersonNumber]  NVARCHAR (50)    CONSTRAINT [DF_Salesperson_SalespersonNumber] DEFAULT ('') NOT NULL,
    [Name]               NVARCHAR (100)   CONSTRAINT [DF_Salesperson_Salesperson] DEFAULT ('') NOT NULL,
    [SalesClass]         NVARCHAR (50)    CONSTRAINT [DF_Salesperson_SalesClass] DEFAULT ('') NOT NULL,
    [Code]               NVARCHAR (50)    CONSTRAINT [DF_Salesperson_Code] DEFAULT ('') NOT NULL,
    [ReferenceNumber]    NVARCHAR (50)    CONSTRAINT [DF_Salesperson_ReferenceNumber] DEFAULT ('') NOT NULL,
    [IsOutsideRep]       BIT              CONSTRAINT [DF_Salesperson_OutsideRep] DEFAULT ((0)) NOT NULL,
    [SalesPeriodToDate]  DECIMAL (18, 5)  CONSTRAINT [DF_Salesperson_SalesPeriodToDate] DEFAULT ((0)) NOT NULL,
    [SalesYearToDate]    DECIMAL (18, 5)  CONSTRAINT [DF_Salesperson_SalesYearToDate] DEFAULT ((0)) NOT NULL,
    [Email]              NVARCHAR (128)   CONSTRAINT [DF_Salesperson_Email] DEFAULT ('') NOT NULL,
    [Phone1]             NVARCHAR (50)    CONSTRAINT [DF_Salesperson_Phone1] DEFAULT ('') NOT NULL,
    [Phone2]             NVARCHAR (50)    CONSTRAINT [DF_Salesperson_Phone2] DEFAULT ('') NOT NULL,
    [Title]              NVARCHAR (100)   CONSTRAINT [DF_Salesperson_Title] DEFAULT ('') NOT NULL,
    [ParentId]           UNIQUEIDENTIFIER NULL,
    [UserProfileId]      UNIQUEIDENTIFIER NULL,
    [ImagePath]          NVARCHAR (1024)  CONSTRAINT [DF_Salesperson_ImagePath] DEFAULT ('') NOT NULL,
    [Description]        NVARCHAR (1024)  CONSTRAINT [DF_Salesperson_Description] DEFAULT ('') NOT NULL,
    [MinMarginAllowed]   DECIMAL (18, 5)  CONSTRAINT [DF_Salesperson_MinMarginAllowed] DEFAULT ((0)) NOT NULL,
    [MaxDiscountPercent] DECIMAL (18, 5)  CONSTRAINT [DF_Salesperson_MaxDiscountPercent] DEFAULT ((0)) NOT NULL,
    [SalesManagerId]     UNIQUEIDENTIFIER NULL,
    [CreatedOn]          DATETIME2 (7)    CONSTRAINT [DF_Salesperson_CreatedOn] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]          NVARCHAR (100)   CONSTRAINT [DF_Salesperson_CreatedBy] DEFAULT ('') NOT NULL,
    [ModifiedOn]         DATETIME2 (7)    CONSTRAINT [DF_Salesperson_ModifiedOn] DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]         NVARCHAR (100)   CONSTRAINT [DF_Salesperson_ModifiedBy] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_Salesperson] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [CK_Salesperson_SalespersonNumber] CHECK (len([SalespersonNumber])>(0)),
    CONSTRAINT [FK_Salesperson_SalesManager] FOREIGN KEY ([SalesManagerId]) REFERENCES [dbo].[Salesperson] ([Id]),
    CONSTRAINT [FK_Salesperson_UserProfile] FOREIGN KEY ([UserProfileId]) REFERENCES [dbo].[UserProfile] ([Id]) ON DELETE SET NULL
);

