CREATE TABLE [dbo].[TradeServicesProduct.OLD] (
    [CUSTOMER_Item ID]                     BIGINT         NULL,
    [CUSTOMER_Manufacturer Name]           VARCHAR (22)   NULL,
    [CUSTOMER_Manufacturer Part Number]    VARCHAR (13)   NULL,
    [CUSTOMER_Description]                 VARCHAR (38)   NULL,
    [CUSTOMER_UPC]                         BIGINT         NULL,
    [CUSTOMER_Price Line]                  VARCHAR (8)    NULL,
    [MANUFACTURER NAME]                    VARCHAR (53)   NULL,
    [MANUFACTURER PART NUMBER]             VARCHAR (17)   NULL,
    [SHORT DESCRIPTION]                    VARCHAR (79)   NULL,
    [PRODUCT NAME]                         VARCHAR (26)   NULL,
    [BRAND SERIES NAME]                    VARCHAR (42)   NULL,
    [UPC ]                                 BIGINT         NULL,
    [UNSPSC CODE]                          BIGINT         NULL,
    [TS SCHEMA PARENT CLASS NAME]          VARCHAR (29)   NULL,
    [TS SCHEMA LEAF CLASS NAME]            VARCHAR (23)   NULL,
    [Attribute Name_1]                     VARCHAR (19)   NULL,
    [Attribute Value_1]                    VARCHAR (75)   NULL,
    [Attribute Name_2]                     VARCHAR (19)   NULL,
    [Attribute Value_2]                    VARCHAR (104)  NULL,
    [Attribute Name_3]                     VARCHAR (20)   NULL,
    [Attribute Value_3]                    VARCHAR (61)   NULL,
    [Attribute Name_4]                     VARCHAR (18)   NULL,
    [Attribute Value_4]                    VARCHAR (32)   NULL,
    [Attribute Name_5]                     VARCHAR (21)   NULL,
    [Attribute Value_5]                    VARCHAR (57)   NULL,
    [Attribute Name_6]                     VARCHAR (19)   NULL,
    [Attribute Value_6]                    VARCHAR (19)   NULL,
    [Attribute Name_7]                     VARCHAR (21)   NULL,
    [Attribute Value_7]                    VARCHAR (93)   NULL,
    [Attribute Name_8]                     VARCHAR (24)   NULL,
    [Attribute Value_8]                    VARCHAR (47)   NULL,
    [Attribute Name_9]                     VARCHAR (24)   NULL,
    [Attribute Value_9]                    VARCHAR (173)  NULL,
    [Attribute Name_10]                    VARCHAR (20)   NULL,
    [Attribute Value_10]                   VARCHAR (59)   NULL,
    [Attribute Name_11]                    VARCHAR (19)   NULL,
    [Attribute Value_11]                   VARCHAR (66)   NULL,
    [Attribute Name_12]                    VARCHAR (23)   NULL,
    [Attribute Value_12]                   VARCHAR (114)  NULL,
    [Attribute Name_13]                    VARCHAR (21)   NULL,
    [Attribute Value_13]                   VARCHAR (19)   NULL,
    [Attribute Name_14]                    VARCHAR (19)   NULL,
    [Attribute Value_14]                   VARCHAR (113)  NULL,
    [Attribute Name_15]                    VARCHAR (22)   NULL,
    [Attribute Value_15]                   VARCHAR (290)  NULL,
    [Attribute Name_16]                    VARCHAR (19)   NULL,
    [Attribute Value_16]                   VARCHAR (45)   NULL,
    [Attribute Name_17]                    VARCHAR (25)   NULL,
    [Attribute Value_17]                   VARCHAR (278)  NULL,
    [Attribute Name_18]                    VARCHAR (20)   NULL,
    [Attribute Value_18]                   VARCHAR (384)  NULL,
    [Attribute Name_19]                    VARCHAR (21)   NULL,
    [Attribute Value_19]                   VARCHAR (119)  NULL,
    [Attribute Name_20]                    VARCHAR (25)   NULL,
    [Attribute Value_20]                   VARCHAR (11)   NULL,
    [Attribute Name_21]                    VARCHAR (20)   NULL,
    [Attribute Value_21]                   VARCHAR (25)   NULL,
    [Attribute Name_22]                    VARCHAR (10)   NULL,
    [Attribute Value_22]                   VARCHAR (MAX)  NULL,
    [ADDITONAL INFORMATION]                VARCHAR (325)  NULL,
    [ LONG DESCRIPTION]                    VARCHAR (1072) NULL,
    [FEATURES BENEFITS]                    VARCHAR (1302) NULL,
    [PACKAGE WEIGHT  (pounds)]             FLOAT (53)     NULL,
    [PACKAGE WIDTH  (inch)]                FLOAT (53)     NULL,
    [PACKAGE LENGTH  (inch)]               FLOAT (53)     NULL,
    [PACKAGE HEIGHT  (inch)]               FLOAT (53)     NULL,
    [PACKAGE VOLUME  (cubic inch)]         FLOAT (53)     NULL,
    [COUNTRY OF ORIGIN]                    VARCHAR (3)    NULL,
    [LEAD FREE  (Yes or No)]               VARCHAR (3)    NULL,
    [MERCURY FREE  (Yes or No)]            VARCHAR (MAX)  NULL,
    [WATER SENSE SAVER  (Yes or No)]       VARCHAR (3)    NULL,
    [ENERGY STAR RATED  (Yes or No)]       VARCHAR (MAX)  NULL,
    [IMAGE  (Standard)]                    VARCHAR (76)   NULL,
    [MFR CATALOG DOCUMENT]                 VARCHAR (80)   NULL,
    [MFR SPECIFICATION TECHNICAL DOCUMENT] VARCHAR (77)   NULL,
    [MFR MSDS DOCUMENT]                    VARCHAR (MAX)  NULL,
    [MFR INSTALLATION OPERATOR  DOCUMENT]  VARCHAR (79)   NULL,
    [TS_STATUS]                            VARCHAR (8)    NULL,
    [TS_COMMENTS FOR CUSTOMER]             VARCHAR (42)   NULL,
    [ADDITIONAL URL_1  (Mfr Item Page)]    VARCHAR (192)  NULL,
    [ADDITIONAL URL_2]                     VARCHAR (169)  NULL
);

