CREATE TABLE [dbo].[UserProfile] (
    [Id]                        UNIQUEIDENTIFIER CONSTRAINT [DF_UserProfile_UserProfileId] DEFAULT (newsequentialid()) NOT NULL,
    [FirstName]                 NVARCHAR (100)   CONSTRAINT [DF_UserProfile_FirstName] DEFAULT ('') NOT NULL,
    [LastName]                  NVARCHAR (100)   CONSTRAINT [DF_UserProfile_LastName] DEFAULT ('') NOT NULL,
    [Company]                   NVARCHAR (100)   CONSTRAINT [DF_UserProfile_Company] DEFAULT ('') NOT NULL,
    [Phone]                     NVARCHAR (50)    CONSTRAINT [DF_UserProfile_Phone] DEFAULT ('') NOT NULL,
    [Extension]                 NVARCHAR (50)    CONSTRAINT [DF_UserProfile_Ext] DEFAULT ('') NOT NULL,
    [Fax]                       NVARCHAR (50)    CONSTRAINT [DF_UserProfile_Fax] DEFAULT ('') NOT NULL,
    [Position]                  NVARCHAR (100)   CONSTRAINT [DF_UserProfile_Position] DEFAULT ('') NOT NULL,
    [UserName]                  NVARCHAR (256)   CONSTRAINT [DF_UserProfile_UserName] DEFAULT ('') NOT NULL,
    [CanChangePassword]         BIT              CONSTRAINT [DF_UserProfile_CanChangePassword] DEFAULT ((0)) NOT NULL,
    [CanSubmitOrder]            BIT              CONSTRAINT [DF_UserProfile_CanSubmitOrder] DEFAULT ((0)) NOT NULL,
    [CanViewAllOrders]          BIT              CONSTRAINT [DF_UserProfile_CanViewAllOrders] DEFAULT ((0)) NOT NULL,
    [IsSubscribed]              BIT              CONSTRAINT [DF_UserProfile_IsSubscribed] DEFAULT ((0)) NOT NULL,
    [ApplicationName]           NVARCHAR (256)   CONSTRAINT [DF_UserProfile_ApplicationName] DEFAULT (N'/') NOT NULL,
    [SubscriptionUser]          BIT              CONSTRAINT [DF_UserProfile_SubscriptionUser] DEFAULT ((0)) NOT NULL,
    [IsGuest]                   BIT              CONSTRAINT [DF_UserProfile_IsGuest] DEFAULT ((0)) NOT NULL,
    [Email]                     NVARCHAR (256)   CONSTRAINT [DF_UserProfile_Email] DEFAULT ('') NOT NULL,
    [IsReviewingContent]        BIT              CONSTRAINT [DF_UserProfile_IsReviewingContent] DEFAULT ((0)) NOT NULL,
    [DefaultCustomerId]         UNIQUEIDENTIFIER NULL,
    [ApproverUserProfileId]     UNIQUEIDENTIFIER NULL,
    [LimitExceededNotification] BIT              CONSTRAINT [DF_UserProfile_LimitExceededNotification] DEFAULT ((0)) NOT NULL,
    [IsEditingContent]          BIT              CONSTRAINT [DF_UserProfile_IsEditingContent] DEFAULT ((0)) NOT NULL,
    [DashboardIsHomepage]       BIT              CONSTRAINT [DF_UserProfile_DashboardIsHomepage] DEFAULT ((0)) NOT NULL,
    [CurrencyId]                UNIQUEIDENTIFIER NULL,
    [IsPasswordChangeRequired]  BIT              CONSTRAINT [DF_UserProfile_IsPasswordChangeRequired] DEFAULT ((0)) NOT NULL,
    [HasRfqUpdates]             BIT              CONSTRAINT [DF_UserProfile_HasRfqUpdates] DEFAULT ((0)) NOT NULL,
    [LanguageId]                UNIQUEIDENTIFIER NULL,
    [CreatedOn]                 DATETIME2 (7)    CONSTRAINT [DF_UserProfile_CreatedOn] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                 NVARCHAR (100)   CONSTRAINT [DF_UserProfile_CreatedBy] DEFAULT ('') NOT NULL,
    [ModifiedOn]                DATETIME2 (7)    CONSTRAINT [DF_UserProfile_ModifiedOn] DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]                NVARCHAR (100)   CONSTRAINT [DF_UserProfile_ModifiedBy] DEFAULT ('') NOT NULL,
    [PasswordChangedOn]         DATETIME2 (7)    CONSTRAINT [DF_UserProfile_PasswordChangedOn] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_UserProfile] PRIMARY KEY CLUSTERED ([Id] ASC)
);

